// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCEz0wiznDRJAg1HwV4y8lGt0KWikEL1s',
    appId: '1:703220616599:web:d4de127ad5e10d0e9348d2',
    messagingSenderId: '703220616599',
    projectId: 'ice-app-ae083',
    authDomain: 'ice-app-ae083.firebaseapp.com',
    storageBucket: 'ice-app-ae083.appspot.com',
    measurementId: 'G-VVVJL6FKT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8vKUAfD4pcfhzMvtklWT0sU7QnaPyd-E',
    appId: '1:703220616599:android:e537d6c5d80911f29348d2',
    messagingSenderId: '703220616599',
    projectId: 'ice-app-ae083',
    storageBucket: 'ice-app-ae083.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdSy2nqIFAIFFJgcgSVXFMU08C5F7oV0',
    appId: '1:703220616599:ios:80a376c063da4f3b9348d2',
    messagingSenderId: '703220616599',
    projectId: 'ice-app-ae083',
    storageBucket: 'ice-app-ae083.appspot.com',
    androidClientId: '703220616599-8j3u4it96p9vhvjcjhh52qq5nu66k6lq.apps.googleusercontent.com',
    iosClientId: '703220616599-9lgpfksmita720jg462n1ak8qma527dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.iceApp',
  );
}
